export const teams = [
  {
    abbreviation: "NJD",
    city: "New Jersey",
    name: "Devils",
  },
  {
    abbreviation: "NYI",
    city: "New York",
    name: "Islanders",
  },
  {
    abbreviation: "NYR",
    city: "New York",
    name: "Rangers",
  },
  {
    abbreviation: "PHI",
    city: "Philadelphia",
    name: "Flyers",
  },
  {
    abbreviation: "PIT",
    city: "Pittsburgh",
    name: "Penguins",
  },
  {
    abbreviation: "BOS",
    city: "Boston",
    name: "Bruins",
  },
  {
    abbreviation: "BUF",
    city: "Buffalo",
    name: "Sabres",
  },
  {
    abbreviation: "MTL",
    city: "Montréal",
    name: "Canadiens",
  },
  {
    abbreviation: "OTT",
    city: "Ottawa",
    name: "Senators",
  },
  {
    abbreviation: "TOR",
    city: "Toronto",
    name: "Maple Leafs",
  },
  {
    abbreviation: "CAR",
    city: "Carolina",
    name: "Hurricanes",
  },
  {
    abbreviation: "FLA",
    city: "Florida",
    name: "Panthers",
  },
  {
    abbreviation: "TBL",
    city: "Tampa Bay",
    name: "Lightning",
  },
  {
    abbreviation: "WSH",
    city: "Washington",
    name: "Capitals",
  },
  {
    abbreviation: "CHI",
    city: "Chicago",
    name: "Blackhawks",
  },
  {
    abbreviation: "DET",
    city: "Detroit",
    name: "Red Wings",
  },
  {
    abbreviation: "NSH",
    city: "Nashville",
    name: "Predators",
  },
  {
    abbreviation: "STL",
    city: "St. Louis",
    name: "Blues",
  },
  {
    abbreviation: "CGY",
    city: "Calgary",
    name: "Flames",
  },
  {
    abbreviation: "COL",
    city: "Colorado",
    name: "Avalanche",
  },
  {
    abbreviation: "EDM",
    city: "Edmonton",
    name: "Oilers",
  },
  {
    abbreviation: "VAN",
    city: "Vancouver",
    name: "Canucks",
  },
  {
    abbreviation: "ANA",
    city: "Anaheim",
    name: "Ducks",
  },
  {
    abbreviation: "DAL",
    city: "Dallas",
    name: "Stars",
  },
  {
    abbreviation: "LAK",
    city: "Los Angeles",
    name: "Kings",
  },
  {
    abbreviation: "SJS",
    city: "San Jose",
    name: "Sharks",
  },
  {
    abbreviation: "CBJ",
    city: "Columbus",
    name: "Blue Jackets",
  },
  {
    abbreviation: "MIN",
    city: "Minnesota",
    name: "Wild",
  },
  {
    abbreviation: "WPG",
    city: "Winnipeg",
    name: "Jets",
  },
  {
    abbreviation: "ARI",
    city: "Arizona",
    name: "Coyotes",
  },
  {
    abbreviation: "VGK",
    city: "Vegas",
    name: "Golden Knights",
  },
  {
    abbreviation: "SEA",
    city: "Seattle",
    name: "Kraken",
  },
]

export const teamStats = [
  {
    games_played: 51,
    losses: 9,
    points: 76,
    rank: 2,
    team: "Carolina Hurricanes",
    wins: 34,
  },
  {
    games_played: 51,
    losses: 13,
    points: 72,
    rank: 3,
    team: "New Jersey Devils",
    wins: 34,
  },
  {
    games_played: 51,
    losses: 14,
    points: 66,
    rank: 7,
    team: "New York Rangers",
    wins: 29,
  },
  {
    games_played: 53,
    losses: 20,
    points: 60,
    rank: 13,
    team: "Washington Capitals",
    wins: 27,
  },
  {
    games_played: 50,
    losses: 16,
    points: 59,
    rank: 14,
    team: "Pittsburgh Penguins",
    wins: 25,
  },
  {
    games_played: 55,
    losses: 23,
    points: 59,
    rank: 15,
    team: "New York Islanders",
    wins: 27,
  },
  {
    games_played: 53,
    losses: 22,
    points: 53,
    rank: 22,
    team: "Philadelphia Flyers",
    wins: 22,
  },
  {
    games_played: 51,
    losses: 32,
    points: 34,
    rank: 32,
    team: "Columbus Blue Jackets",
    wins: 15,
  },
  {
    games_played: 51,
    losses: 7,
    points: 83,
    rank: 1,
    team: "Boston Bruins",
    wins: 39,
  },
  {
    games_played: 52,
    losses: 13,
    points: 70,
    rank: 4,
    team: "Toronto Maple Leafs",
    wins: 31,
  },
  {
    games_played: 51,
    losses: 16,
    points: 68,
    rank: 6,
    team: "Tampa Bay Lightning",
    wins: 33,
  },
  {
    games_played: 54,
    losses: 22,
    points: 58,
    rank: 19,
    team: "Florida Panthers",
    wins: 26,
  },
  {
    games_played: 50,
    losses: 20,
    points: 56,
    rank: 20,
    team: "Buffalo Sabres",
    wins: 26,
  },
  {
    games_played: 50,
    losses: 20,
    points: 52,
    rank: 23,
    team: "Detroit Red Wings",
    wins: 22,
  },
  {
    games_played: 50,
    losses: 23,
    points: 51,
    rank: 24,
    team: "Ottawa Senators",
    wins: 24,
  },
  {
    games_played: 51,
    losses: 27,
    points: 44,
    rank: 27,
    team: "Montréal Canadiens",
    wins: 20,
  },
  {
    games_played: 53,
    losses: 13,
    points: 70,
    rank: 5,
    team: "Dallas Stars",
    wins: 30,
  },
  {
    games_played: 52,
    losses: 19,
    points: 65,
    rank: 9,
    team: "Winnipeg Jets",
    wins: 32,
  },
  {
    games_played: 50,
    losses: 19,
    points: 58,
    rank: 16,
    team: "Colorado Avalanche",
    wins: 27,
  },
  {
    games_played: 51,
    losses: 20,
    points: 58,
    rank: 17,
    team: "Minnesota Wild",
    wins: 27,
  },
  {
    games_played: 49,
    losses: 19,
    points: 54,
    rank: 21,
    team: "Nashville Predators",
    wins: 24,
  },
  {
    games_played: 51,
    losses: 25,
    points: 49,
    rank: 25,
    team: "St. Louis Blues",
    wins: 23,
  },
  {
    games_played: 51,
    losses: 28,
    points: 40,
    rank: 29,
    team: "Arizona Coyotes",
    wins: 17,
  },
  {
    games_played: 49,
    losses: 29,
    points: 35,
    rank: 31,
    team: "Chicago Blackhawks",
    wins: 15,
  },
  {
    games_played: 53,
    losses: 18,
    points: 66,
    rank: 8,
    team: "Vegas Golden Knights",
    wins: 31,
  },
  {
    games_played: 51,
    losses: 17,
    points: 63,
    rank: 10,
    team: "Seattle Kraken",
    wins: 29,
  },
  {
    games_played: 52,
    losses: 18,
    points: 63,
    rank: 11,
    team: "Edmonton Oilers",
    wins: 29,
  },
  {
    games_played: 53,
    losses: 18,
    points: 63,
    rank: 12,
    team: "Los Angeles Kings",
    wins: 28,
  },
  {
    games_played: 52,
    losses: 18,
    points: 58,
    rank: 18,
    team: "Calgary Flames",
    wins: 24,
  },
  {
    games_played: 52,
    losses: 27,
    points: 46,
    rank: 26,
    team: "Vancouver Canucks",
    wins: 21,
  },
  {
    games_played: 53,
    losses: 26,
    points: 43,
    rank: 28,
    team: "San Jose Sharks",
    wins: 16,
  },
  {
    games_played: 52,
    losses: 29,
    points: 40,
    rank: 30,
    team: "Anaheim Ducks",
    wins: 17,
  },
]

export const playerStats = [
  {
    assists: 53,
    goals: 41,
    id: 8478402,
    name: "Connor McDavid",
    points: 94,
  },
  {
    assists: 47,
    goals: 29,
    id: 8477934,
    name: "Leon Draisaitl",
    points: 76,
  },
  {
    assists: 56,
    goals: 20,
    id: 8476453,
    name: "Nikita Kucherov",
    points: 76,
  },
  {
    assists: 34,
    goals: 38,
    id: 8477956,
    name: "David Pastrnak",
    points: 72,
  },
  {
    assists: 44,
    goals: 27,
    id: 8479314,
    name: "Matthew Tkachuk",
    points: 71,
  },
  {
    assists: 53,
    goals: 17,
    id: 8474578,
    name: "Erik Karlsson",
    points: 70,
  },
  {
    assists: 36,
    goals: 33,
    id: 8480027,
    name: "Jason Robertson",
    points: 69,
  },
  {
    assists: 34,
    goals: 34,
    id: 8479420,
    name: "Tage Thompson",
    points: 68,
  },
  {
    assists: 32,
    goals: 35,
    id: 8481559,
    name: "Jack Hughes",
    points: 67,
  },
  {
    assists: 39,
    goals: 24,
    id: 8480012,
    name: "Elias Pettersson",
    points: 63,
  },
]
